### ISSUE TITLE
Webhook not working

### ISSUE THREAD

**Issue by Luongzz** [J-295/youtube-webhook#3]

**Comment by J-295** [comment]
Was this working previously? Are there any errors?

**Comment by J-295** [comment]
> Ah some channels work, some don't

Would you be ok sharing the list from your config?

**Comment by J-295** [comment]
Were any videos deleted from any of the channels?

**Comment by J-295** [comment]
It isn't clear why this has happened then, though I do plan to change how new videos are recognised which will fix a couple of issues.
